import "./components/app-avatar-image-fallback.component.scss"
import "./components/app-toggle-card.component.scss"
import "./components/app-stat-card.component.scss"
import "./components/app-star-rating-display.component.scss"
import "./components/app-star-rating.component.scss"
import "./components/app-pdf-image-preview.component.scss"
import "./components/app-dropdown.component.scss"

import "./app.ts";
import "./providers/otr-service.provider.ts";
import "./directives/app-fuse-highlight.directive.ts";
import "./components/stat-card/app-stat-card.component.ts";
import "./components/toggle-card/app-toggle-card.component.ts";
import "./components/star-rating/app-star-rating.component.ts";
import "./components/avatar-image-fallback/app-avatar-image-fallback.component.ts";
import "./components/pdf-image-preview/pdf-image-preview.component.ts";
import "./components/courts-dropdown/courts-dropdown.component.ts";
import "./components/courts-dropdown/remote/remote-courts-dropdown.component.ts";
import "./components/violations-dropdown/violations-dropdown.component.ts";
import "./components/star-rating-display/app-star-rating-display.component.ts";
