import '@otr-app/shared-backend-generated-client/dist/typescript/api.module';
import '@otr-app/shared-backend-generated-client/dist/typescript/index';
import './app';
import '../../providers/base-path.provider';
import './router';
import '../../components';
import 'angular-stripe';
import 'angular-credit-cards';
import 'angular-validator/dist/angular-validator.min.js';
